apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - image: adrianding/cicd-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: cicd-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
